# Generated by Django 4.2.5 on 2024-03-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_menu_allergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.sex'),
        ),
    ]
