# Generated by Django 4.2.5 on 2024-03-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='numberOfPeopleMax',
            field=models.IntegerField(default=100),
        ),
    ]
