# Generated by Django 4.2.5 on 2024-03-23 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_menu_photo_menu_image_menu_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 9, 10, 36, 54546, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 23, 9, 10, 36, 54546, tzinfo=datetime.timezone.utc)),
        ),
    ]
