# Generated by Django 4.2.5 on 2024-03-28 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_menu_upload_date_alter_comment_uploadtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 14, 56, 28, 952282, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='listingDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 28, 14, 56, 28, 952282, tzinfo=datetime.timezone.utc)),
        ),
    ]
