# Generated by Django 4.2.5 on 2024-03-30 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_reserve_note_alter_comment_uploadtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 30, 12, 43, 27, 805628, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='listingDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 30, 12, 43, 27, 805628, tzinfo=datetime.timezone.utc)),
        ),
    ]
